---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # Customize in your overlay.
  storageClassName: STORAGE_CLASS_NAME
  resources:
    requests:
      storage: 1Gi
