---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../busybox/deployment
patches:
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd
