---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      appname: busybox
  replicas: 2
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
        - name: logger
          image: quay.io/nirsof/busybox:stable
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              emit() {
                  echo "$(date) $1" | tee -a /var/log/ramen.log
                  sync
              }
              trap "emit STOP; exit" TERM
              emit START
              while true; do
                  sleep 10 & wait
                  emit UPDATE
              done
          volumeMounts:
            - name: varlog
              mountPath: /var/log
  volumeClaimTemplates:
    - metadata:
        name: varlog
        labels:
          appname: busybox
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rook-ceph-block
        resources:
          requests:
            storage: 1Gi
