---
resources:
  - ../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block

  - target:
      kind: PersistentVolumeClaim
      name: extra-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block
